export const pointData = [
    // {
    //     idCotDiem: 1,
    //     maSV: "SV001",
    //     tenSV: "Nguyen Van A",
    //     diemChuyenCan: 9.0,
    //     diemThucHanh: 8.5,
    //     diemGiuaKy: 7.5,
    //     diemCuoiKy: 8.0,
    //     bangDiemMon: "A",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17A"
    // },
    // {
    //     idCotDiem: 2,
    //     maSV: "SV002",
    //     tenSV: "Le Thi B",
    //     diemChuyenCan: 8.0,
    //     diemThucHanh: 7.5,
    //     diemGiuaKy: 6.5,
    //     diemCuoiKy: 7.0,
    //     bangDiemMon: "B+",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17A"
    // },
    // {
    //     idCotDiem: 3,
    //     maSV: "SV003",
    //     tenSV: "Tran Van C",
    //     diemChuyenCan: 7.5,
    //     diemThucHanh: 7.0,
    //     diemGiuaKy: 7.0,
    //     diemCuoiKy: 7.5,
    //     bangDiemMon: "B",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17A"
    // },
    // {
    //     idCotDiem: 4,
    //     maSV: "SV004",
    //     tenSV: "Pham Thi D",
    //     diemChuyenCan: 9.0,
    //     diemThucHanh: 9.0,
    //     diemGiuaKy: 8.5,
    //     diemCuoiKy: 9.0,
    //     bangDiemMon: "A+",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17A"
    // },
    // {
    //     idCotDiem: 5,
    //     maSV: "SV005",
    //     tenSV: "Hoang Van E",
    //     diemChuyenCan: 6.5,
    //     diemThucHanh: 6.0,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 6.5,
    //     bangDiemMon: "C+",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17A"
    // },
    // {
    //     idCotDiem: 6,
    //     maSV: "SV006",
    //     tenSV: "Do Thi F",
    //     diemChuyenCan: 7.0,
    //     diemThucHanh: 7.5,
    //     diemGiuaKy: 8.0,
    //     diemCuoiKy: 8.5,
    //     bangDiemMon: "B+",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17B"
    // },
    // {
    //     idCotDiem: 7,
    //     maSV: "SV007",
    //     tenSV: "Nguyen Van G",
    //     diemChuyenCan: 5.0,
    //     diemThucHanh: 6.0,
    //     diemGiuaKy: 5.5,
    //     diemCuoiKy: 6.0,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17B"
    // },
    // {
    //     idCotDiem: 8,
    //     maSV: "SV008",
    //     tenSV: "Le Thi H",
    //     diemChuyenCan: 10.0,
    //     diemThucHanh: 9.5,
    //     diemGiuaKy: 9.0,
    //     diemCuoiKy: 9.5,
    //     bangDiemMon: "A+",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17B"
    // },
    // {
    //     idCotDiem: 9,
    //     maSV: "SV009",
    //     tenSV: "Tran Van I",
    //     diemChuyenCan: 7.0,
    //     diemThucHanh: 8.0,
    //     diemGiuaKy: 7.5,
    //     diemCuoiKy: 8.0,
    //     bangDiemMon: "B+",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // },
    // {
    //     idCotDiem: 10,
    //     maSV: "SV010",
    //     tenSV: "Pham Thi K",
    //     diemChuyenCan: 6.0,
    //     diemThucHanh: 5.5,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 5.5,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // },
    // {
    //     idCotDiem: 10,
    //     maSV: "SV010",
    //     tenSV: "Pham Thi K",
    //     diemChuyenCan: 6.0,
    //     diemThucHanh: 5.5,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 5.5,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // }, {
    //     idCotDiem: 10,
    //     maSV: "SV010",
    //     tenSV: "Pham Thi K",
    //     diemChuyenCan: 6.0,
    //     diemThucHanh: 5.5,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 5.5,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // },
    // {
    //     idCotDiem: 10,
    //     maSV: "SV010",
    //     tenSV: "Pham Thi K",
    //     diemChuyenCan: 6.0,
    //     diemThucHanh: 5.5,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 5.5,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // }, {
    //     idCotDiem: 10,
    //     maSV: "SV010",
    //     tenSV: "Pham Thi K",
    //     diemChuyenCan: 6.0,
    //     diemThucHanh: 5.5,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 5.5,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // },
    // {
    //     idCotDiem: 10,
    //     maSV: "SV010",
    //     tenSV: "Pham Thi K",
    //     diemChuyenCan: 6.0,
    //     diemThucHanh: 5.5,
    //     diemGiuaKy: 6.0,
    //     diemCuoiKy: 5.5,
    //     bangDiemMon: "C",
    //     hocKy: 1,
    //     nam: "2024-2025",
    //     lop: "DHKTPM17C"
    // }
];
