export interface TrainingProgram {
    idThongTinChung: number;
    tenChuongTrinh: string;
    bac: string;
    loaiBang: string;
    loaiHinhDaoTao: string;
    thoiGian: string;
    soTinChi: number;
    khoaQuanLy: string;
    ngonNgu: string;
    khoaTuyen: string;
  }
  
  export const trainingPrograms: TrainingProgram[] = [
    {
      idThongTinChung: 1,
      tenChuongTrinh: "Công nghệ thông tin",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4 năm",
      soTinChi: 120,
      khoaQuanLy: "Khoa CNTT",
      ngonNgu: "Tiếng Anh",
      khoaTuyen: "Khoa 2023",
    },
    {
      idThongTinChung: 2,
      tenChuongTrinh: "Kỹ thuật cơ khí",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4 năm",
      soTinChi: 130,
      khoaQuanLy: "Khoa Cơ khí",
      ngonNgu: "Tiếng Việt",
      khoaTuyen: "Khoa 2022",
    },
    {
      idThongTinChung: 3,
      tenChuongTrinh: "Kinh tế quốc tế",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Liên kết",
      thoiGian: "3.5 năm",
      soTinChi: 110,
      khoaQuanLy: "Khoa Kinh tế",
      ngonNgu: "Tiếng Anh",
      khoaTuyen: "Khoa 2024",
    },
    {
      idThongTinChung: 4,
      tenChuongTrinh: "Ngôn ngữ Anh",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4 năm",
      soTinChi: 115,
      khoaQuanLy: "Khoa Ngoại ngữ",
      ngonNgu: "Tiếng Anh",
      khoaTuyen: "Khoa 2023",
    },
    {
      idThongTinChung: 5,
      tenChuongTrinh: "Quản trị kinh doanh",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4 năm",
      soTinChi: 125,
      khoaQuanLy: "Khoa Kinh tế",
      ngonNgu: "Tiếng Việt",
      khoaTuyen: "Khoa 2022",
    },
    {
      idThongTinChung: 6,
      tenChuongTrinh: "Kỹ thuật điện",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4.5 năm",
      soTinChi: 135,
      khoaQuanLy: "Khoa Điện",
      ngonNgu: "Tiếng Việt",
      khoaTuyen: "Khoa 2021",
    },
    {
      idThongTinChung: 7,
      tenChuongTrinh: "Luật kinh tế",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Liên kết",
      thoiGian: "4 năm",
      soTinChi: 120,
      khoaQuanLy: "Khoa Luật",
      ngonNgu: "Tiếng Việt",
      khoaTuyen: "Khoa 2023",
    },
    {
      idThongTinChung: 8,
      tenChuongTrinh: "Thiết kế đồ họa",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4 năm",
      soTinChi: 110,
      khoaQuanLy: "Khoa Mỹ thuật",
      ngonNgu: "Tiếng Anh",
      khoaTuyen: "Khoa 2024",
    },
    {
      idThongTinChung: 9,
      tenChuongTrinh: "Y khoa",
      bac: "Đại học",
      loaiBang: "Bác sĩ",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "6 năm",
      soTinChi: 180,
      khoaQuanLy: "Khoa Y",
      ngonNgu: "Tiếng Việt",
      khoaTuyen: "Khoa 2020",
    },
    {
      idThongTinChung: 10,
      tenChuongTrinh: "Khoa học dữ liệu",
      bac: "Đại học",
      loaiBang: "Cử nhân",
      loaiHinhDaoTao: "Chính quy",
      thoiGian: "4 năm",
      soTinChi: 120,
      khoaQuanLy: "Khoa CNTT",
      ngonNgu: "Tiếng Anh",
      khoaTuyen: "Khoa 2023",
    },
  ];